### ISSUE TITLE
ERROR in ./app/ts/vendor.ts (You may need an appropriate loader to handle this file type)

### ISSUE THREAD

**Issue by karelbecerra** [ng-book/angular2-redux-chat#2]
node --version
v6.9.1
npm --version
3.10.9

(it fails in Ubuntu and Mac)

ERROR in ./app/ts/vendor.ts
Module parse failed: /home/karel/dev/projects/tests/chatbot/angular2-redux-chat/node_modules/tslint-loader/index.js!/home/karel/dev/projects/tests/chatbot/angular2-redux-chat/app/ts/vendor.ts Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
| // Polyfills
| import 'core-js/es6';
| import 'core-js/es6';
| import 'core-js/es7/reflect';
 @ multi vendor

Let me know if you need additional info. 

Thanks

**Comment by auser** [comment]
Karel,
I can't replicate your error. Did you ever get this to work?

**Comment by karelbecerra** [comment]
Yes, is working and unfortunately I don't have details right now (I think was related with loader version)
