### ISSUE TITLE
export 'Store' was not found in 'redux' in build

### ISSUE THREAD

**Issue by gsudhesh** [ng-book/angular2-redux-chat#5]
Why i'm getting these errors?

WARNING in ./src/app/app.component.ts
43:57-62 "export 'Store' was not found in 'redux'

WARNING in ./src/app/app.component.ts
43:82-87 "export 'Store' was not found in 'redux'

**Comment by kevin-sakemaer** [comment]
I got the same error

**Comment by Yonben** [comment]
Same for me :/

Edit: by the way, as a workaround you can replace `import { State } from 'redux'` by `import * as Redux from 'redux'` and use `Redux.Store` instead of simply `Store`, it worked for me.
